version: "2"

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shopping
      - POSTGRES_USER=root
  # web:
  #   build: .
  #   working_dir: /code
  #   volumes: 
  #     - .:/code
  #   ports:
  #     - "8080:8080"
  #     - "5858:5858"
  #   depends_on:
  #     - "db"
  #   links: 
  #     - "db"
  #   command: nodemon --inspect=5858 #npm start
  #   environment: 
  #     - DATABASE_URL=postgres://root@db:5432/shopping

